"""Generate local secrets for the self-hosted Langfuse stack (docker-compose.langfuse.yml).

- Writes .env.langfuse (gitignored) with fresh random secrets and a headless-init project key pair.
- Appends ARCHIVE_LANGFUSE_PUBLIC_KEY / _SECRET_KEY / _HOST to the root .env only if none are present.
- Never prints secret values and never overwrites an existing file or key.

Usage (repo root):  python deploy/langfuse/make_env.py [--archive-host http://langfuse:3000] [--port 3100]
"""

from __future__ import annotations

import argparse
import secrets
import sys
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def _hex(n: int) -> str:
    return secrets.token_hex(n)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--archive-host", default="http://langfuse:3000",
                    help="URL the archive api/worker use to reach Langfuse (shared Docker network alias by default)")
    ap.add_argument("--port", type=int, default=3100, help="host port for the UI (bound to 127.0.0.1)")
    ap.add_argument("--admin-email", default="langfuse-admin@archive.local")
    args = ap.parse_args()

    lf_env = ROOT / ".env.langfuse"
    if lf_env.exists():
        print(f"{lf_env.name} already exists; not overwritten.")
    else:
        pg, ch, redis, minio = _hex(24), _hex(24), _hex(24), _hex(24)
        pk, sk = f"pk-lf-{uuid.uuid4()}", f"sk-lf-{uuid.uuid4()}"
        s3 = {"BUCKET": "langfuse", "REGION": "auto", "ACCESS_KEY_ID": "langfuse-minio",
              "SECRET_ACCESS_KEY": minio, "ENDPOINT": "http://minio:9000", "FORCE_PATH_STYLE": "true"}
        lines = [
            "# Self-hosted Langfuse secrets (local demo). Generated by deploy/langfuse/make_env.py. NEVER COMMIT.",
            f"NEXTAUTH_URL=http://localhost:{args.port}",
            f"NEXTAUTH_SECRET={_hex(32)}",
            f"SALT={_hex(32)}",
            f"ENCRYPTION_KEY={_hex(32)}",
            "TELEMETRY_ENABLED=false",
            "AUTH_DISABLE_SIGNUP=true",
            "LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=false",
            "POSTGRES_USER=langfuse",
            f"POSTGRES_PASSWORD={pg}",
            "POSTGRES_DB=langfuse",
            f"DATABASE_URL=postgresql://langfuse:{pg}@postgres:5432/langfuse",
            "CLICKHOUSE_DB=default",
            "CLICKHOUSE_USER=clickhouse",
            f"CLICKHOUSE_PASSWORD={ch}",
            "CLICKHOUSE_URL=http://clickhouse:8123",
            "CLICKHOUSE_MIGRATION_URL=clickhouse://clickhouse:9000",
            "CLICKHOUSE_CLUSTER_ENABLED=false",
            "REDIS_HOST=redis",
            "REDIS_PORT=6379",
            f"REDIS_AUTH={redis}",
            "MINIO_ROOT_USER=langfuse-minio",
            f"MINIO_ROOT_PASSWORD={minio}",
            *[f"LANGFUSE_S3_EVENT_UPLOAD_{k}={v}" for k, v in s3.items()],
            "LANGFUSE_S3_EVENT_UPLOAD_PREFIX=events/",
            *[f"LANGFUSE_S3_MEDIA_UPLOAD_{k}={v}" for k, v in s3.items()],
            "LANGFUSE_S3_MEDIA_UPLOAD_PREFIX=media/",
            "LANGFUSE_INIT_ORG_ID=ambedkar-archive",
            "LANGFUSE_INIT_ORG_NAME=Ambedkar Digital Heritage Archive",
            "LANGFUSE_INIT_PROJECT_ID=archive-demo",
            "LANGFUSE_INIT_PROJECT_NAME=Archive demo (redacted traces)",
            f"LANGFUSE_INIT_PROJECT_PUBLIC_KEY={pk}",
            f"LANGFUSE_INIT_PROJECT_SECRET_KEY={sk}",
            f"LANGFUSE_INIT_USER_EMAIL={args.admin_email}",
            "LANGFUSE_INIT_USER_NAME=Archive admin",
            f"LANGFUSE_INIT_USER_PASSWORD={secrets.token_urlsafe(24)}",
        ]
        lf_env.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"wrote {lf_env.name} (values not shown)")

    keys = dict(line.split("=", 1) for line in lf_env.read_text(encoding="utf-8").splitlines()
                if "=" in line and not line.startswith("#"))
    root_env = ROOT / ".env"
    existing = root_env.read_text(encoding="utf-8") if root_env.exists() else ""
    names = {ln.split("=", 1)[0].strip() for ln in existing.splitlines() if "=" in ln and not ln.lstrip().startswith("#")}
    wanted = ["ARCHIVE_LANGFUSE_PUBLIC_KEY", "ARCHIVE_LANGFUSE_SECRET_KEY", "ARCHIVE_LANGFUSE_HOST"]
    if names & set(wanted):
        print("root .env already has ARCHIVE_LANGFUSE_* keys; left unchanged.")
        return 0
    block = ("" if existing.endswith("\n") or not existing else "\n") + (
        "# Self-hosted Langfuse (redacted traces only; see docs/LANGFUSE.md)\n"
        f"ARCHIVE_LANGFUSE_PUBLIC_KEY={keys['LANGFUSE_INIT_PROJECT_PUBLIC_KEY']}\n"
        f"ARCHIVE_LANGFUSE_SECRET_KEY={keys['LANGFUSE_INIT_PROJECT_SECRET_KEY']}\n"
        f"ARCHIVE_LANGFUSE_HOST={args.archive_host}\n")
    with root_env.open("a", encoding="utf-8", newline="\n") as fh:
        fh.write(block)
    print("appended ARCHIVE_LANGFUSE_* to root .env (values not shown)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
