"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 20:16:29.218000
"""
from __future__ import annotations

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


AUDIT_TRIGGER = """
CREATE OR REPLACE FUNCTION audit_event_append_only() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'audit_event is append-only';
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER audit_event_no_update BEFORE UPDATE OR DELETE ON audit_event
  FOR EACH ROW EXECUTE FUNCTION audit_event_append_only();
"""


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('index_version', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('answer_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_hash', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('question_ref', sa.Text(), nullable=False),
    sa.Column('passages_retrieved', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('index_version', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('provider_latency_ms', sa.Integer(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('retried_retrieval', sa.Boolean(), nullable=False),
    sa.Column('validation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('entity_version', sa.Integer(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checksum_before', sa.String(length=64), nullable=True),
    sa.Column('checksum_after', sa.String(length=64), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_setting',
    sa.Column('collection', sa.String(length=20), nullable=False),
    sa.Column('machine_translation_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('collection')
    )
    op.create_table('dataset_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=False),
    sa.Column('languages', postgresql.ARRAY(sa.String(length=5)), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('passage_count', sa.Integer(), nullable=False),
    sa.Column('permission_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('split_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gate_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_ready', 'job', ['status', 'run_after'], unique=False)
    op.create_table('kiosk_sync',
    sa.Column('device_id', sa.String(length=80), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('manifest_version', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('knowledge_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.String(length=30), nullable=False),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('item_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qr_collection',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('entries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('review_decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('before', sa.Text(), nullable=True),
    sa.Column('after', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reviewer', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_seeded_fixture', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rights_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=120), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_institution', sa.Text(), nullable=False),
    sa.Column('edition', sa.Text(), nullable=True),
    sa.Column('volume', sa.Text(), nullable=True),
    sa.Column('pages', sa.Text(), nullable=True),
    sa.Column('rights_holder', sa.Text(), nullable=False),
    sa.Column('basis_for_use', sa.Text(), nullable=False),
    sa.Column('display_permission', sa.String(length=20), nullable=False),
    sa.Column('training_permission', sa.String(length=20), nullable=False),
    sa.Column('training_basis', sa.Text(), nullable=True),
    sa.Column('external_processing', sa.String(length=20), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('attribution', sa.Text(), nullable=False),
    sa.Column('date_checked', sa.Date(), nullable=False),
    sa.Column('checked_by', sa.Text(), nullable=False),
    sa.Column('discovery_only', sa.Boolean(), nullable=False),
    sa.Column('is_fixture', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("display_permission IN ('allowed', 'not_allowed', 'unknown')", name='ck_display_permission_values'),
    sa.CheckConstraint("external_processing IN ('allowed', 'not_allowed', 'unknown')", name='ck_external_processing_values'),
    sa.CheckConstraint("training_permission IN ('allowed', 'not_allowed', 'unknown')", name='ck_training_permission_values'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key')
    )
    op.create_table('staff_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String(length=30)), nullable=False),
    sa.Column('languages', postgresql.ARRAY(sa.String(length=5)), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('titles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('narration_file_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('curator', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('system_state',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('timeline_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_text', sa.Text(), nullable=False),
    sa.Column('sort_date', sa.Date(), nullable=False),
    sa.Column('date_certainty', sa.String(length=20), nullable=False),
    sa.Column('titles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('descriptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('item_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('node_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('curator', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archival_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('collection', sa.String(length=20), nullable=False),
    sa.Column('source_institution', sa.Text(), nullable=False),
    sa.Column('creator', sa.Text(), nullable=True),
    sa.Column('date_text', sa.Text(), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('date_certainty', sa.String(length=20), nullable=False),
    sa.Column('original_languages', postgresql.ARRAY(sa.String(length=5)), nullable=False),
    sa.Column('scripts', postgresql.ARRAY(sa.String(length=10)), nullable=False),
    sa.Column('edition', sa.Text(), nullable=True),
    sa.Column('volume', sa.Text(), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('rights_record_id', sa.Integer(), nullable=False),
    sa.Column('access_level', sa.String(length=30), nullable=False),
    sa.Column('publication_state', sa.String(length=20), nullable=False),
    sa.Column('published_version_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('capture_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ndli_links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_fixture', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawal_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("access_level IN ('public', 'public_online_only', 'restricted')", name='ck_access_level_values'),
    sa.CheckConstraint("collection IN ('writings', 'speeches', 'debates', 'manuscripts', 'photographs', 'audio_video')", name='ck_collection_values'),
    sa.CheckConstraint("item_type IN ('text', 'printed_scan', 'manuscript', 'photograph', 'audio', 'video')", name='ck_item_type_values'),
    sa.CheckConstraint("publication_state IN ('draft', 'in_review', 'approved', 'staged', 'published', 'withdrawn')", name='ck_publication_state_values'),
    sa.ForeignKeyConstraint(['rights_record_id'], ['rights_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_edge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_node', sa.Integer(), nullable=False),
    sa.Column('to_node', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(length=40), nullable=False),
    sa.Column('evidence_passage_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_item_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('proposed_by', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['from_node'], ['knowledge_node.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node'], ['knowledge_node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('base_model', sa.Text(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=True),
    sa.Column('training_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('code_commit', sa.Text(), nullable=True),
    sa.Column('evaluation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('size', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weights_uri', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('index_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_example',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('origin', sa.String(length=30), nullable=False),
    sa.Column('positive_passage_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hard_negative_passage_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hard_negative_status', sa.String(length=20), nullable=False),
    sa.Column('split', sa.String(length=10), nullable=True),
    sa.Column('group_key', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('verification', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleaned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['archival_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'version_no')
    )
    op.create_table('media_segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.Text(), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Text(), nullable=True),
    sa.Column('quote_verified', sa.Boolean(), nullable=False),
    sa.Column('quote_verified_by', sa.Text(), nullable=True),
    sa.Column('quote_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['archival_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_metadata',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('people', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('place', sa.Text(), nullable=True),
    sa.Column('event', sa.Text(), nullable=True),
    sa.Column('date_text', sa.Text(), nullable=True),
    sa.Column('date_certainty', sa.String(length=20), nullable=False),
    sa.Column('photographer', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('visible_text', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['archival_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('review_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('page_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sample_page_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['archival_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('printed_page_label', sa.String(length=40), nullable=True),
    sa.Column('image_file_id', sa.Integer(), nullable=True),
    sa.Column('delivery_file_id', sa.Integer(), nullable=True),
    sa.Column('doc_class', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('preprocessing_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ocr_route', sa.String(length=20), nullable=False),
    sa.Column('gate_version', sa.String(length=40), nullable=True),
    sa.Column('quality_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gate_passed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('review_mode', sa.String(length=10), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('review_priority', sa.Float(), nullable=False),
    sa.Column('phash', sa.String(length=32), nullable=True),
    sa.Column('approved_text', sa.Text(), nullable=True),
    sa.Column('approved_text_version', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quote_verified', sa.Boolean(), nullable=False),
    sa.Column('quote_verified_by', sa.Text(), nullable=True),
    sa.Column('quote_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sarvam_attempts', sa.Integer(), nullable=False),
    sa.Column('sarvam_last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("doc_class IN ('born_digital', 'printed', 'handwritten', 'photograph', 'audio_video')", name='ck_doc_class_values'),
    sa.CheckConstraint("ocr_route IN ('text_layer', 'local', 'sarvam', 'manual', 'none')", name='ck_ocr_route_values'),
    sa.CheckConstraint("status IN ('pending', 'ocr_done', 'needs_full_review', 'sarvam_pending', 'manual_transcription', 'in_batch_review', 'approved', 'rejected')", name='ck_status_values'),
    sa.ForeignKeyConstraint(['batch_id'], ['review_batch.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['archival_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'sequence')
    )
    op.create_table('file_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('format', sa.String(length=80), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('derived_from_id', sa.Integer(), nullable=True),
    sa.Column('generator', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['derived_from_id'], ['file_version.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['archival_item.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_file_sha_role', 'file_version', ['sha256', 'role'], unique=False)
    op.create_table('passage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_version_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('media_segment_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('translation_of_id', sa.Integer(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('bboxes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('text_version', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('quote_verified', sa.Boolean(), nullable=False),
    sa.Column('quote_verifier', sa.Text(), nullable=True),
    sa.Column('quote_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_basis', sa.String(length=30), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('embedding_model', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Text(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('indexed', sa.Boolean(), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector(CASE WHEN language = 'en' THEN 'english'::regconfig ELSE 'simple'::regconfig END, text)", persisted=True), nullable=False),
    sa.CheckConstraint("(page_id IS NOT NULL) OR (media_segment_id IS NOT NULL) OR kind = 'reviewed_caption'", name='ck_passage_anchor'),
    sa.ForeignKeyConstraint(['item_id'], ['archival_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_version_id'], ['item_version.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_segment_id'], ['media_segment.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.ForeignKeyConstraint(['translation_of_id'], ['passage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_passage_item_version', 'passage', ['item_id', 'item_version_id'], unique=False)
    op.create_index('ix_passage_tsv', 'passage', ['tsv'], unique=False, postgresql_using='gin')
    op.create_table('citation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('passage_id', sa.Integer(), nullable=False),
    sa.Column('quoted_span', sa.Text(), nullable=True),
    sa.Column('span_verified', sa.Boolean(), nullable=False),
    sa.Column('display_label', sa.Text(), nullable=False),
    sa.Column('deep_link', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer_log.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passage_id'], ['passage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('derivative',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('source_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('generator', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('label_shown', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file_version.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['archival_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(length=40), nullable=False),
    sa.Column('engine_version', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('hocr_file_id', sa.Integer(), nullable=True),
    sa.Column('words', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mean_confidence', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('raw_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hocr_file_id'], ['file_version.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_passage_id', sa.Integer(), nullable=True),
    sa.Column('source_field', sa.Text(), nullable=True),
    sa.Column('target_language', sa.String(length=5), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewer', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_passage_id'], ['passage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.create_foreign_key('fk_item_published_version', 'archival_item', 'item_version',
                          ['published_version_id'], ['id'])
    op.create_foreign_key('fk_page_image_file', 'page', 'file_version', ['image_file_id'], ['id'])
    op.create_foreign_key('fk_page_delivery_file', 'page', 'file_version', ['delivery_file_id'], ['id'])
    op.create_index('ix_passage_embedding_hnsw', 'passage', ['embedding'], postgresql_using='hnsw',
                    postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.execute(AUDIT_TRIGGER)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_event_no_update ON audit_event")
    op.execute("DROP FUNCTION IF EXISTS audit_event_append_only()")
    op.drop_constraint('fk_item_published_version', 'archival_item', type_='foreignkey')
    op.drop_constraint('fk_page_image_file', 'page', type_='foreignkey')
    op.drop_constraint('fk_page_delivery_file', 'page', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translation')
    op.drop_table('ocr_result')
    op.drop_table('derivative')
    op.drop_table('citation')
    op.drop_index('ix_passage_tsv', table_name='passage', postgresql_using='gin')
    op.drop_index('ix_passage_item_version', table_name='passage')
    op.drop_table('passage')
    op.drop_index('ix_file_sha_role', table_name='file_version')
    op.drop_table('file_version')
    op.drop_table('page')
    op.drop_table('review_batch')
    op.drop_table('photo_metadata')
    op.drop_table('media_segment')
    op.drop_table('item_version')
    op.drop_table('training_example')
    op.drop_table('model_version')
    op.drop_table('knowledge_edge')
    op.drop_table('archival_item')
    op.drop_table('timeline_event')
    op.drop_table('system_state')
    op.drop_table('story')
    op.drop_table('staff_user')
    op.drop_table('rights_record')
    op.drop_table('review_decision')
    op.drop_table('qr_collection')
    op.drop_table('knowledge_node')
    op.drop_table('kiosk_sync')
    op.drop_index('ix_job_ready', table_name='job')
    op.drop_table('job')
    op.drop_table('dataset_version')
    op.drop_table('collection_setting')
    op.drop_table('audit_event')
    op.drop_table('answer_log')
    op.drop_table('answer_cache')
    # ### end Alembic commands ###
