"""Curated links from approved debate passages to Constitution articles (spec 5.5 knowledge map).

Links are made by curators, never generated. Passage ids change on every republication, so a link is
anchored to its page or media segment plus the text hash of the passage it was made on, and is resolved
to the passage of the item's current published version at read time.
"""

from __future__ import annotations

import re
from collections import defaultdict
from typing import Any

from sqlalchemy import select
from sqlalchemy.orm import Session

from archive.models import ArchivalItem, ConstitutionArticle, ConstitutionLink, Passage, RightsRecord
from archive.rights import item_visible

ARTICLE_NOTE = ("Links between debate passages and Constitution articles are curated by archive staff. "
                "They are not generated by AI.")


def article_title(article: ConstitutionArticle, language: str = "en") -> str:
    titles = article.titles or {}
    return titles.get(language) or titles.get("en") or next(iter(titles.values()), "")


def _current_passages(db: Session, links: list[ConstitutionLink]) -> dict[int, Passage]:
    """link id -> passage in the item's current published version (source text, not translations)."""
    if not links:
        return {}
    item_ids = {lk.item_id for lk in links}
    rows = db.execute(
        select(Passage).join(ArchivalItem, Passage.item_id == ArchivalItem.id)
        .where(Passage.item_id.in_(item_ids), Passage.item_version_id == ArchivalItem.published_version_id,
               Passage.translation_of_id.is_(None), Passage.indexed.is_(True))
        .order_by(Passage.char_start, Passage.id)
    ).scalars().all()
    by_page: dict[int, list[Passage]] = defaultdict(list)
    by_seg: dict[int, list[Passage]] = defaultdict(list)
    for p in rows:
        if p.page_id is not None:
            by_page[p.page_id].append(p)
        if p.media_segment_id is not None:
            by_seg[p.media_segment_id].append(p)
    out: dict[int, Passage] = {}
    for lk in links:
        candidates = by_seg.get(lk.media_segment_id, []) if lk.media_segment_id else by_page.get(lk.page_id, [])
        if not candidates:
            continue
        out[lk.id] = next((p for p in candidates if p.text_hash == lk.text_hash), candidates[0])
    return out


def active_links(db: Session, *, item_ids: list[int] | None = None, article_number: str | None = None,
                 visible_only: bool = True) -> list[ConstitutionLink]:
    stmt = select(ConstitutionLink).where(ConstitutionLink.removed_at.is_(None))
    if item_ids is not None:
        if not item_ids:
            return []
        stmt = stmt.where(ConstitutionLink.item_id.in_(item_ids))
    if article_number is not None:
        stmt = stmt.where(ConstitutionLink.article_number == article_number)
    if visible_only:
        stmt = stmt.join(ArchivalItem, ConstitutionLink.item_id == ArchivalItem.id).join(
            RightsRecord, ArchivalItem.rights_record_id == RightsRecord.id).where(item_visible())
    return list(db.execute(stmt.order_by(ConstitutionLink.id)).scalars())


def resolved_links(db: Session, links: list[ConstitutionLink]) -> list[tuple[ConstitutionLink, Passage | None]]:
    current = _current_passages(db, links)
    return [(lk, current.get(lk.id)) for lk in links]


def _articles(db: Session, numbers: set[str]) -> dict[str, ConstitutionArticle]:
    if not numbers:
        return {}
    rows = db.execute(select(ConstitutionArticle).where(ConstitutionArticle.number.in_(numbers))).scalars()
    return {a.number: a for a in rows}


def _chip(article: ConstitutionArticle, language: str) -> dict[str, str]:
    return {"number": article.number, "title": article_title(article, language)}


def articles_by_anchor(db: Session, item_id: int, language: str = "en") -> tuple[dict[int, list], dict[int, list]]:
    """(page_id -> article chips, media_segment_id -> article chips) for one visible item."""
    links = active_links(db, item_ids=[item_id])
    arts = _articles(db, {lk.article_number for lk in links})
    pages: dict[int, list[dict[str, str]]] = defaultdict(list)
    segs: dict[int, list[dict[str, str]]] = defaultdict(list)
    for lk in links:
        chip = _chip(arts[lk.article_number], language)
        target = segs[lk.media_segment_id] if lk.media_segment_id else pages[lk.page_id]
        if chip not in target:
            target.append(chip)
    return pages, segs


def articles_by_passage(db: Session, passages: list[Passage], language: str = "en") -> dict[int, list]:
    """passage id -> article chips. Translations inherit the links of the passage they translate."""
    item_ids = sorted({p.item_id for p in passages})
    links = active_links(db, item_ids=item_ids, visible_only=False)
    if not links:
        return {}
    arts = _articles(db, {lk.article_number for lk in links})
    by_source: dict[int, list[dict[str, str]]] = defaultdict(list)
    for lk, p in resolved_links(db, links):
        if p is None:
            continue
        chip = _chip(arts[lk.article_number], language)
        if chip not in by_source[p.id]:
            by_source[p.id].append(chip)
    out: dict[int, list] = {}
    for p in passages:
        chips = by_source.get(p.translation_of_id or p.id)
        if chips:
            out[p.id] = chips
    return out


def article_index(db: Session) -> list[dict[str, Any]]:
    """Articles with at least one visible link, in constitutional order."""
    links = active_links(db)
    counts: dict[str, set[int]] = defaultdict(set)
    for lk, p in resolved_links(db, links):
        if p is not None:
            counts[lk.article_number].add(lk.id)
    arts = _articles(db, set(counts))
    return [{"number": a.number, "titles": a.titles, "part": a.part, "debates": len(counts[a.number])}
            for a in sorted(arts.values(), key=lambda a: article_sort_key(a.number))]


def article_sort_key(number: str) -> tuple[int, str]:
    m = re.match(r"\d+", number)
    return (int(m.group()) if m else 0, number)
