import { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { createMemoryRouter, RouterProvider } from "react-router-dom";
import { afterEach, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import { routes } from "./App";
import { SessionProvider } from "./state";
import { fakeFetch } from "./__fixtures__/visitor";
import { STRINGS, type Lang } from "./i18n";

declare global {
  var IS_REACT_ACT_ENVIRONMENT: boolean;
}

vi.setConfig({ testTimeout: 30_000 });

const LANGS: Lang[] = ["en", "hi", "mr"];
let root: Root | null = null;
let host: HTMLElement | null = null;

beforeAll(() => {
  globalThis.IS_REACT_ACT_ENVIRONMENT = true;
  window.matchMedia ??= ((query: string) => ({ matches: false, media: query, addEventListener() {}, removeEventListener() {}, addListener() {}, removeListener() {}, onchange: null, dispatchEvent: () => false })) as unknown as typeof window.matchMedia;
  Element.prototype.scrollIntoView ??= () => {};
});

beforeEach(() => {
  vi.stubGlobal("fetch", vi.fn(fakeFetch));
  sessionStorage.clear();
  localStorage.clear();
});

afterEach(async () => {
  await act(async () => root?.unmount());
  root = null;
  host?.remove();
  host = null;
  vi.unstubAllGlobals();
});

async function mount(path: string, ready: string, lang: Lang) {
  sessionStorage.setItem("archive-visit", JSON.stringify({ lang, textScale: 1, contrast: false, askHistory: [], sessionId: "test", basket: [] }));
  host = document.createElement("div");
  document.body.append(host);
  root = createRoot(host);
  const router = createMemoryRouter(routes, { initialEntries: [path] });
  await act(async () => root!.render(<SessionProvider><RouterProvider router={router} /></SessionProvider>));
  for (let i = 0; i < 200 && !document.querySelector(ready); i++) await act(async () => { await new Promise((r) => setTimeout(r, 0)); });
  expect(document.querySelector(ready), `${ready} on ${path}`).not.toBeNull();
}

const text = (sel: string) => document.querySelector(sel)?.textContent ?? "";

describe.each(LANGS)("Ask is labelled as AI-powered wherever it is offered (%s)", (lang) => {
  it("home Ask button and the Ask link in the main menu say AI", async () => {
    await mount("/", ".bigsearch", lang);
    const askButton = [...document.querySelectorAll<HTMLButtonElement>(".bigsearch button")].find((b) => b.type === "button");
    expect(askButton?.textContent).toBe(STRINGS[lang].askButton);
    expect(askButton?.textContent).toContain("AI");
    expect(text("nav a[href='/ask']")).toContain("AI");
  });

  it("Ask page title, explanation, question box and submit button say AI", async () => {
    await mount("/ask", "#ask-q", lang);
    expect(text("h1")).toContain("AI");
    expect(document.title).toContain("AI");
    expect(text(".page > p.muted")).toContain("AI");
    const box = document.querySelector<HTMLTextAreaElement>("#ask-q")!;
    expect(box.placeholder).toContain("AI");
    expect(text("label[for='ask-q']")).toContain("AI");
    expect(text(".ask-form button[type=submit]")).toContain("AI");
  });

  it("a cited answer is marked as AI-generated, and stays marked when it is paraphrase-only", async () => {
    vi.stubGlobal("fetch", vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => {
      const res = await fakeFetch(input, init);
      if (init?.method !== "POST") return res;
      const body = { ...(await res.json()), paraphrase_only: true };
      return new Response(JSON.stringify(body), { status: 200, headers: { "Content-Type": "application/json" } });
    }));
    await mount("/ask?q=What%20is%20caste%3F", ".answer .cite-link", lang);
    const chips = [...document.querySelectorAll(".answer .label-row .chip")].map((c) => c.textContent);
    expect(text(".answer .chip.ai")).toBe(STRINGS[lang].askLabel);
    expect(text(".answer .chip.ai")).toContain("AI");
    expect(chips).toContain(STRINGS[lang].askParaphrase);
  });
});

describe("Ask page explanation (English source copy)", () => {
  it("says the answer comes from an AI model, can be wrong, and quotes are exact only when marked verified", () => {
    const lead = STRINGS.en.askLead;
    expect(lead).toMatch(/generated by an AI model from approved archive passages/);
    expect(lead).toMatch(/can be wrong/);
    expect(lead).toMatch(/quote-verified/);
  });
});
